/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsakpore;

/**
 *
 * @author HP
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profil
     */
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Kasir = new javax.swing.JPanel();
        Kasir = new javax.swing.JLabel();
        Tombol_Dashboard = new javax.swing.JButton();
        Tombol_DataMaster = new javax.swing.JButton();
        Tombol_Transaksi = new javax.swing.JButton();
        Tombol_Pengaturan = new javax.swing.JButton();
        garis_kasir = new javax.swing.JPanel();
        Background_atas = new javax.swing.JPanel();
        PT_SMEA = new javax.swing.JLabel();
        PROFILE = new javax.swing.JLabel();
        tempat_foto = new javax.swing.JLabel();
        garis = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        Kelola_Pengguna = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        MasukkanNama = new javax.swing.JTextField();
        MasukkanEMAIL = new javax.swing.JTextField();
        Nama1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Logo3 = new javax.swing.JLabel();
        Kelola_Pengguna1 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        Nama3 = new javax.swing.JLabel();
        MasukkanNama1 = new javax.swing.JTextField();
        MasukkanEMAIL1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Nama4 = new javax.swing.JLabel();
        MasukkanEMAIL2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background_Kasir.setBackground(new java.awt.Color(153, 153, 153));

        Kasir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Kasir.setForeground(new java.awt.Color(255, 255, 255));
        Kasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kasir.setText("Kasir");

        Tombol_Dashboard.setBackground(new java.awt.Color(153, 153, 153));
        Tombol_Dashboard.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Tombol_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_Dashboard.setText("Dashboard");
        Tombol_Dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Tombol_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_DashboardActionPerformed(evt);
            }
        });

        Tombol_DataMaster.setBackground(new java.awt.Color(153, 153, 153));
        Tombol_DataMaster.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Tombol_DataMaster.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_DataMaster.setText("Data Master");
        Tombol_DataMaster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Tombol_DataMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_DataMasterActionPerformed(evt);
            }
        });

        Tombol_Transaksi.setBackground(new java.awt.Color(153, 153, 153));
        Tombol_Transaksi.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Tombol_Transaksi.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_Transaksi.setText("Transaksi");
        Tombol_Transaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Tombol_Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_TransaksiActionPerformed(evt);
            }
        });

        Tombol_Pengaturan.setBackground(new java.awt.Color(153, 153, 153));
        Tombol_Pengaturan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Tombol_Pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_Pengaturan.setText("Pengaturan");
        Tombol_Pengaturan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Tombol_Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_PengaturanActionPerformed(evt);
            }
        });

        garis_kasir.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout garis_kasirLayout = new javax.swing.GroupLayout(garis_kasir);
        garis_kasir.setLayout(garis_kasirLayout);
        garis_kasirLayout.setHorizontalGroup(
            garis_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        garis_kasirLayout.setVerticalGroup(
            garis_kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Background_KasirLayout = new javax.swing.GroupLayout(Background_Kasir);
        Background_Kasir.setLayout(Background_KasirLayout);
        Background_KasirLayout.setHorizontalGroup(
            Background_KasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_KasirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Background_KasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tombol_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tombol_Transaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tombol_DataMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tombol_Pengaturan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_KasirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(garis_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Background_KasirLayout.setVerticalGroup(
            Background_KasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_KasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kasir)
                .addGap(1, 1, 1)
                .addComponent(garis_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tombol_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tombol_DataMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tombol_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tombol_Pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(857, Short.MAX_VALUE))
        );

        getContentPane().add(Background_Kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        Background_atas.setBackground(new java.awt.Color(255, 255, 255));

        PT_SMEA.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        PT_SMEA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PT_SMEA.setText("PT SMEA NO SEITO DESU");

        PROFILE.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        PROFILE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PROFILE.setText("PROFILE");

        tempat_foto.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\iconusername150px.png")); // NOI18N
        tempat_foto.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        garis.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout garisLayout = new javax.swing.GroupLayout(garis);
        garis.setLayout(garisLayout);
        garisLayout.setHorizontalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        garisLayout.setVerticalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Logo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\iconusername25px.png")); // NOI18N

        Kelola_Pengguna.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Kelola_Pengguna.setText("KELOLA PENGGUNA :");

        Nama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nama.setText("NAMA :");

        MasukkanNama.setForeground(new java.awt.Color(204, 204, 204));
        MasukkanNama.setText("Masukkan Nama");
        MasukkanNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MasukkanNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukkanNamaActionPerformed(evt);
            }
        });

        MasukkanEMAIL.setForeground(new java.awt.Color(204, 204, 204));
        MasukkanEMAIL.setText("Masukkan Email");
        MasukkanEMAIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MasukkanEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukkanEMAILActionPerformed(evt);
            }
        });

        Nama1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nama1.setText("EMAIL :");

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Logo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\iconusername25px.png")); // NOI18N

        Kelola_Pengguna1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Kelola_Pengguna1.setText("GANTI PASSWORD");

        Nama2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nama2.setText("USERNAME :");

        Nama3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nama3.setText("PASSWORD :");

        MasukkanNama1.setForeground(new java.awt.Color(204, 204, 204));
        MasukkanNama1.setText("Masukkan Username");
        MasukkanNama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MasukkanNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukkanNama1ActionPerformed(evt);
            }
        });

        MasukkanEMAIL1.setForeground(new java.awt.Color(204, 204, 204));
        MasukkanEMAIL1.setText("Masukkan Password");
        MasukkanEMAIL1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MasukkanEMAIL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukkanEMAIL1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UBAH PASSWORD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Nama4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nama4.setText("SANDI :");

        MasukkanEMAIL2.setForeground(new java.awt.Color(204, 204, 204));
        MasukkanEMAIL2.setText("Masukkan Sandi");
        MasukkanEMAIL2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MasukkanEMAIL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukkanEMAIL2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Background_atasLayout = new javax.swing.GroupLayout(Background_atas);
        Background_atas.setLayout(Background_atasLayout);
        Background_atasLayout.setHorizontalGroup(
            Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(garis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background_atasLayout.createSequentialGroup()
                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_atasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PT_SMEA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PROFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Background_atasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tempat_foto)
                        .addGap(18, 18, 18)
                        .addComponent(Logo2)
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Background_atasLayout.createSequentialGroup()
                                        .addComponent(Nama)
                                        .addGap(18, 18, 18)
                                        .addComponent(MasukkanNama, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Background_atasLayout.createSequentialGroup()
                                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Nama1)
                                            .addComponent(Nama4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MasukkanEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MasukkanEMAIL2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(280, 280, 280))
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(Kelola_Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Logo3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nama3)
                                    .addComponent(Nama2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MasukkanNama1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MasukkanEMAIL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(Kelola_Pengguna1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(233, 233, 233)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        Background_atasLayout.setVerticalGroup(
            Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_atasLayout.createSequentialGroup()
                .addComponent(PT_SMEA, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PROFILE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempat_foto)
                    .addGroup(Background_atasLayout.createSequentialGroup()
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Kelola_Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Kelola_Pengguna1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MasukkanNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MasukkanNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MasukkanEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MasukkanEMAIL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(Background_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MasukkanEMAIL2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nama4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Background_atasLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
        );

        getContentPane().add(Background_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1810, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tombol_DashboardActionPerformed

    private void Tombol_TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_TransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tombol_TransaksiActionPerformed

    private void Tombol_DataMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_DataMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tombol_DataMasterActionPerformed

    private void Tombol_PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_PengaturanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tombol_PengaturanActionPerformed

    private void MasukkanNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukkanNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukkanNamaActionPerformed

    private void MasukkanEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukkanEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukkanEMAILActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MasukkanNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukkanNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukkanNama1ActionPerformed

    private void MasukkanEMAIL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukkanEMAIL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukkanEMAIL1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MasukkanEMAIL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukkanEMAIL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukkanEMAIL2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_Kasir;
    private javax.swing.JPanel Background_atas;
    private javax.swing.JLabel Kasir;
    private javax.swing.JLabel Kelola_Pengguna;
    private javax.swing.JLabel Kelola_Pengguna1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JTextField MasukkanEMAIL;
    private javax.swing.JTextField MasukkanEMAIL1;
    private javax.swing.JTextField MasukkanEMAIL2;
    private javax.swing.JTextField MasukkanNama;
    private javax.swing.JTextField MasukkanNama1;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel Nama2;
    private javax.swing.JLabel Nama3;
    private javax.swing.JLabel Nama4;
    private javax.swing.JLabel PROFILE;
    private javax.swing.JLabel PT_SMEA;
    private javax.swing.JButton Tombol_Dashboard;
    private javax.swing.JButton Tombol_DataMaster;
    private javax.swing.JButton Tombol_Pengaturan;
    private javax.swing.JButton Tombol_Transaksi;
    private javax.swing.JPanel garis;
    private javax.swing.JPanel garis_kasir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel tempat_foto;
    // End of variables declaration//GEN-END:variables
}
